### ISSUE TITLE
show every finding in new page

### ISSUE THREAD

**Issue by effortlessdevsec** [pwndoc-ng/pwndoc-ng#269]
how can i create report with every finding in new page

**Comment by diggidong** [comment]
You have to use word's `<CTRL>`+`<ENTER>` functionality.
When creating your template:

```
{findings}
<CTRL>+<ENTER>
{#description}
...
{/findings}
```

It's important to have the first `{findings}` on the prior page, because, if I remember correctly, in a case where you don't have an entry in `{findings}`, this can result in a blank page, which is not wanted. But I am not sure about this one.

**Comment by Klego** [comment]
I did the same but I use <CTRL>+<ENTER> at the end of the findings section and it works just fine too
