### ISSUE TITLE
Pwndoc-ng docs

### ISSUE THREAD

**Issue by JulianGR** [pwndoc-ng/pwndoc-ng#31]
Hello,

Since there are changed in the pwndoc-ng docs and the project doesn't have the docs online, I think it would be nice if you can create a GitHub pages with the docs, just like original pwndoc repo has.

**Comment by Zeecka** [comment]
I agree, the ReadMe need to be fixed too and some features are not documented yet.

**Comment by JulianGR** [comment]
Allright, if you add me to collaborators, could I set up the GitHub pages? or do I need full access to the account of pwndoc-ng?

**Comment by JulianGR** [comment]
@Zeecka ping

**Comment by Zeecka** [comment]
@JulianGR one of the previous developper I used to work with on pwndoc asked me for the same thing. Github pages need full access on the repo, and I will only give it to the ones who actively work(ed) on the project for now.
However, he managed to setup Github pages quickly, and since Github pages are working now, you can make PR on the documentation if you want to.

**Comment by JulianGR** [comment]
> Github pages need full access on the repo, and I will only give it to the ones who actively work(ed) on the project for now.

It makes sense. I didnt mean to specifically get full access, but rather to have the possibility of making PRs to the docs. I'll be making soon changes =)

Keep up the work =)
