### ISSUE TITLE
Missing description text for finding

### ISSUE THREAD

**Issue by RaduNico** [pwndoc-ng/pwndoc-ng#347]
I have an instance of pwndoc-ng running, I am currently trying out to migrate from pwndoc. I noticed that sometimes the finding text description does not appear when accessing a finding. Some other times it loads after a couple (4-5) seconds. The text is there, generating the report result in the correct outcome, it is simply not visible on the web page. Another particularity is that the save finding button appears greyed out.

The web page was previously working correctly. I have encountered this issue on chrome and chromium. Attempting to log in on an incognito window or a different browser works as intended (at least for a while).

![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/40314810/96523d92-059a-4628-9690-c39d55d57e65)

**Comment by Syzik** [comment]
I have the same probleme
I'm trying to investigate

**Comment by Syzik** [comment]
I have the same issue I'm trying to investigate

**Comment by KlimMykhno** [comment]
It's same issue like here: https://github.com/pwndoc-ng/pwndoc-ng/issues/280

**Comment by KlimMykhno** [comment]
@Syzik Could you please review my PR with fix?

**Comment by Syzik** [comment]
Are you certain that this resolves the issue? I have a feeling it might be a cache problem causing the frontend not to display the information properly, which is then overwritten by a backup.

**Comment by KlimMykhno** [comment]
I reproduced this problem by following the steps from #280 and checked how to fix it. There was a problem that in noSync fields have synchronization when you switch tabs, if you switch tabs fast enough hocuspocus is not able to load information and your description and observation are overwritten with empty string. And when you switch between tabs, your finding is empty. If you save finding by miss click or hocuspocus will save it, you will lose your text in database.
That what I found and what I fixed, because I hade same issue yesterday.
